config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'games#index'

  get '/teams/join', to: 'teams#join', as: 'join_team'
  get '/teams/apply', to: 'teams#apply', as: 'apply_team'
  resources :teams

  get '/memberships/show', to: 'memberships#show', as: 'show_memberships'
  resources :memberships

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  state_machine :initial => :to_approve do
    state :to_approve
    state :approved
    state :denied

    event :approve do
      transition [:to_approve] => :approved
    end

    event :deny do
      transition [:to_approve] => :denied
    end
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, uniqueness: true
  has_many :memberships
  has_many :users, through: :memberships
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memberships
  has_many :teams, through: :memberships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  def create user = current_user
    team = Team.find_by_name( membership_params[:team] )
    Membership.create(:team => team, :user => user)
    flash[:notice] = "Request sent"
    redirect_to show_memberships_path
  end

  def show
    @memberships = current_user.memberships
  end

  private
    def membership_params
      params.require(:membership).permit(:team)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :find_team, only: [:show, :apply]

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to @team
      flash[:notice] = "Team created"
    else
      flash[:error] = "Team not created"
      render "new"
    end
  end

  def show
  end

  def join
    @teams = Team.all
    @membership = Membership.new
  end

  def apply
    user = current_user
    unless user.teams.include? @team
      user.teams << team
    end
  end

  private
    def find_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle></button>
    <div class="title-bar-title">Menu</div>
  </div>

  <div class="top-bar" id="example-menu">
    <div class="top-bar-left">
      <ul class="vertical menu" data-responsive-menu="drilldown medium-dropdown" style="width: 300px;">
        <li>
          <a href="#">Verwaltung</a>
          <ul class="vertical menu">
            <li>
              <a href="#">Team</a>
              <ul class="vertical menu">
                <li><%= link_to "Create Team", new_team_path %></li>
                <li><%= link_to "Join Team", join_team_path %></li>
                <li><a href="#">Item 1C</a></li>
                <li><a href="#">Item 1D</a></li>
                <li><a href="#">Item 1E</a></li>
              </ul>
            </li>
            <li><a href="#">Item 1B</a></li>
          </ul>
        </li>
        <li>
          <a href="#">Item 2</a>
          <ul class="vertical menu">
            <li><a href="#">Item 2A</a></li>
            <li><a href="#">Item 2B</a></li>
          </ul>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Login', new_user_session_path)  %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Search"></li>
        <li><button type="button" class="button">Search</button></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <%= render 'layouts/messages' %>
      <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/memberships/show.html.erb
<% @memberships.each do |membership| %>
  <%=membership.team.name%> <%=membership.state%><br>
<%end%>